// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

export const environment = {
  production: false,
  version: env.npm_package_version + '-dev',
  serverUrl: 'https://localhost:5001/api',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US', 'pt-BR'],
  vapidPublicKey:
    'AAAAL3Fd8u8:APA91bGg0KMPRmjXn-PdVwSkXob4Xg3GXMUVSNZdXuOsGDJof6qnaDHY87HaZJUP79Bnu2C8ifeOdgUmw_LDeWU9_0zSooCMuEuSbNVUuc8Q7Xroslo6mB8K8jaZaoquJuB1UIlxCXZ7',
  firebase: {
    apiKey: "AIzaSyBIQH-QtQoL9pMJMH29pn8fRCVJwf7m6I0",
    authDomain: "crudtruck.firebaseapp.com",
    projectId: "crudtruck",
    storageBucket: "crudtruck.appspot.com",
    messagingSenderId: "203765445359",
    appId: "1:203765445359:web:6b9e12339192fa61e9e11a"
  }
};

/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/dist/zone-error';  // Included with Angular CLI.
